name: .NET Core Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Build the project
      run: dotnet build ./src/DntSite.Web/DntSite.Web.csproj -c Release

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_OUTPUT

    - name: Publish the project
      shell: bash
      run: |
        release_name="release-${{ steps.date.outputs.date }}"

        # Build everything
        dotnet publish ./src/DntSite.Web/DntSite.Web.csproj -c Release -o "$release_name"

        # Pack files
        if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./${release_name}/publish/*"
        else
            zip -r "${release_name}.zip" . -i "./${release_name}/publish/*" 
        fi

        # Delete output directory
        rm -r "$release_name"

    - name: Create a release artifact
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "Release_${{ steps.date.outputs.date }}"
        files: "release*"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
